name: Deploy Frontend to GCE

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.GCE_SSH_PASSPHRASE }}

    - name: Deploy to GCE via rsync
      run: |
        rsync -avz --delete dist/ ${{ secrets.GCE_USERNAME }}@${{ secrets.GCE_HOST }}:/var/www/ci-cd-demo/
